interface TranslationMapping {
  [key: string]: {
    [key: string]: string
  }
}

export class SimpleTranslator {
  private languageNames = {
    en: "English",
    hi: "हिंदी (Hindi)",
    ta: "தமிழ் (Tamil)",
    te: "తెలుగు (Telugu)",
    kn: "ಕನ್ನಡ (Kannada)",
    ml: "മലയാളം (Malayalam)",
    gu: "ગુજરાતી (Gujarati)",
  }
private legalTranslations: TranslationMapping = {
  hi: {
    "legal document": "कानूनी दस्तावेज़",
    contract: "अनुबंध",
    agreement: "समझौता",
    party: "पक्ष",
    parties: "पक्षकार",
    obligation: "दायित्व",
    payment: "भुगतान",
    termination: "समाप्ति",
    confidential: "गोपनीय",
    liability: "देयता",
    breach: "उल्लंघन",
    damages: "हर्जाना",
    indemnity: "क्षतिपूर्ति",
    warranty: "वारंटी",
    "intellectual property": "बौद्धिक संपदा",
    jurisdiction: "न्यायाधिकार",
    "governing law": "शासी कानून",
    dispute: "विवाद",
    arbitration: "मध्यस्थता",
    "force majeure": "अप्रत्याशित परिस्थिति",
    summary: "सारांश",
    document: "दस्तावेज़",
    analysis: "विश्लेषण",
    "key points": "मुख्य बिंदु",
    important: "महत्वपूर्ण",
    section: "धारा",
    clause: "खंड",
    terms: "शर्तें",
    conditions: "स्थितियां",
    "employment agreement": "रोजगार समझौता",
    employment: "रोजगार",
    commencement: "आरंभ",
    term: "अवधि",
    "gross negligence": "घोर लापरवाही",
    "written notice": "लिखित सूचना",
    "payment in lieu of notice": "सूचना के बदले भुगतान",
    misconduct: "कदाचार",
    "breach of confidentiality": "गोपनीयता का उल्लंघन",
    employer: "नियोक्ता",
    employee: "कर्मचारी",
    exclusive: "विशेष",
    sole: "एकमात्र",
    created: "निर्मित",
    course: "अवधि",
    continue: "जारी",
    commence: "आरंभ करना",
    terminated: "समाप्त",
    prior: "पूर्व",
    notice: "सूचना",
    days: "दिन",
    this: "यह",
    made: "बनाया गया",
    on: "पर",
    day: "दिन",
    between: "के बीच",
    pvt: "प्राo लिo",
    shall: "होगा",
    any: "कोई",
    by: "द्वारा",
    either: "किसी एक",
    giving: "देते हुए",
    or: "या",
    may: "सकता है",
    case: "स्थिति",
    and: "और",
    laws: "कानून",
    of: "का",
    india: "भारत",
    survive: "बना रहेगा",
    for: "के लिए",
    two: "दो",
    witness: "साक्ष्य",
    written: "लिखित",
    above: "ऊपर",
    in: "में",
    without: "बिना",
    technologies: "प्रौद्योगिकी",
    sunrise: "सनराइज़",
    "is": "है",
    "the": "यह",
    "be": "होना",
    "terminate": "समाप्त करना",
    "lieu": "बदले में",
    "governed": "शासित",
    "a": "एक",
    "period": "अवधि",
    "years": "वर्ष",
    "have": "है",
    "executed": "हस्ताक्षरित",
    "date": "तिथि",
    "first": "प्रथम",
    "Key": "मुख्य",
    "Legal": "कानूनी",
    "Points": "बिंदु",
    "1st": "पहला",
    "November": "नवंबर",
    "2025": "2025",
    "until": "तक",
    "accordance": "अनुसार",
    "property": "संपत्ति",
    "confidentiality": "गोपनीयता",
    "WHEREOF": "जिसके कारण",
    "hereto": "इसके लिए",
    "above": "ऊपर",
    "years": "वर्ष",
    "period": "अवधि",
    "Key": "मुख्य",
    "Legal": "कानूनी",
    "Points": "बिंदु"
  },

  te: {
    "legal document": "చట్టపరమైన పత్రం",
    contract: "ఒప్పందం",
    agreement: "ఒప్పందం",
    party: "పార్టీ",
    parties: "పార్టీలు",
    obligation: "బాధ్యత",
    payment: "చెల్లింపు",
    termination: "ముగింపు",
    confidential: "రహస్యం",
    liability: "బాధ్యత",
    breach: "ఉల్లంఘన",
    damages: "నష్టం",
    indemnity: "నష్టపరిహారం",
    warranty: "వారంటీ",
    "intellectual property": "మేధో సంపత్తి",
    jurisdiction: "అధికార పరిధి",
    "governing law": "పాలక చట్టం",
    dispute: "వివాదం",
    arbitration: "మధ్యవర్తిత్వం",
    "force majeure": "అనివార్య పరిస్థితి",
    summary: "సారాంశం",
    document: "పత్రం",
    analysis: "విశ్లేషణ",
    "key points": "ముఖ్య అంశాలు",
    important: "ముఖ్యమైన",
    section: "విభాగం",
    clause: "నిబంధన",
    terms: "నిబంధనలు",
    conditions: "పరిస్థితులు",
    "employment agreement": "ఉద్యోగ ఒప్పందం",
    employment: "ఉద్యోగం",
    commencement: "ప్రారంభం",
    term: "కాలావధి",
    "gross negligence": "భారీ నిర్లక్ష్యం",
    "written notice": "రాత పూర్వక నోటీసు",
    "payment in lieu of notice": "నోటీసు బదులు చెల్లింపు",
    misconduct: "క్రమశిక్ష లంఘన",
    "breach of confidentiality": "గోప్యత ఉల్లంఘన",
    employer: "ఉద్యోగదాత",
    employee: "ఉద్యోగి",
    exclusive: "ప్రత్యేక",
    sole: "ఒక్కటే",
    created: "సృష్టించిన",
    course: "కాలావధి",
    "continue": "కొనసాగు",
    commence: "ప్రారంభించు",
    terminated: "రద్దుగొన్న",
    prior: "ముందస్తు",
    notice: "నోటీసు",
    days: "రోజులు",
    this: "ఇది",
    made: "తయారు చేయబడింది",
    on: "పై",
    day: "రోజు",
    between: "మధ్య",
    pvt: "పివిటి",
    shall: "చేయాలి",
    any: "ఏదైనా",
    by: "ద్వారా",
    either: "ఏదో ఒకటి",
    giving: "ఇవ్వడం",
    or: "లేదా",
    may: "ఉండవచ్చు",
    case: "కేసు",
    and: "మరియు",
    laws: "చట్టాలు",
    of: "యొక్క",
    india: "భారతదేశం",
    survive: "నిలిచి ఉండండి",
    for: "కోసం",
    two: "రెండు",
    witness: "సాక్షి",
    written: "వ్రాతపూర్వకంగా",
    above: "పైన",
    in: "లో",
    without: "లేకుండా",
    technologies: "సాంకేతికతలు",
    sunrise: "సన్‌రైజ్",
    "is": "అది",
    "1st": "మొదటి",
    "15th": "పదిహేనవ",
    "November": "నవంబర్",
    "2025": "2025",
    "until": "వరకు",
    "accordance": "అనుసరించి",
    "the": "ది",
    "be": "ఉండాలి",
    "property": "ఆస్తి",
    "confidentiality": "గోప్యత",
    "lieu": "బదులుగా",
    "terminate": "రద్దు చేయు",
    "governed": "పాలించబడింది",
    "a": "ఒక",
    "period": "కాలం",
    "years": "సంవత్సరాలు",
    "WHEREOF": "దాంతో",
    "hereto": "ఈ మేరకు",
    "have": "ఉన్నాయి",
    "executed": "సంతకం చేయబడిన",
    "date": "తేదీ",
    "first": "మొదటి",
    "Key": "ప్రధాన",
    "Legal": "చట్టపరమైన",
    "Points": "అంశాలు"
  },

  kn: {
    "legal document": "ಕಾನೂನು ದಾಖಲೆ",
    contract: "ಒಪ್ಪಂದ",
    agreement: "ಒಪ್ಪಂದ",
    party: "ಪಕ್ಷ",
    parties: "ಪಕ್ಷಗಳು",
    obligation: "ಬಾಧ್ಯತೆ",
    payment: "ಪಾವತಿ",
    termination: "ಅಂತ್ಯ",
    confidential: "ಗೌಪ್ಯ",
    liability: "ಹೊಣೆಗಾರಿಕೆ",
    breach: "ಉಲ್ಲಂಘನೆ",
    damages: "ಹಾನಿ",
    indemnity: "ಪರಿಹಾರ",
    warranty: "ವಾರಂಟಿ",
    "intellectual property": "ಬೌದ್ಧಿಕ ಆಸ್ತಿ",
    jurisdiction: "ನ್ಯಾಯಾಧಿಕಾರ",
    "governing law": "ಆಡಳಿತ ಕಾನೂನು",
    dispute: "ವಿವಾದ",
    arbitration: "ಮಧ್ಯಸ್ಥಿಕೆ",
    "force majeure": "ಅನಿವಾರ್ಯ ಸ್ಥಿತಿ",
    summary: "ಸಾರಾಂಶ",
    document: "ದಾಖಲೆ",
    analysis: "ವಿಶ್ಲೇಷಣೆ",
    "key points": "ಮುಖ್ಯ ಅಂಶಗಳು",
    important: "ಮುಖ್ಯ",
    section: "ವಿಭಾಗ",
    clause: "ಷರತ್ತು",
    terms: "ನಿಯಮಗಳು",
    conditions: "ಪರಿಸ್ಥಿತಿಗಳು",
    "employment agreement": "ಉದ್ಯೋಗ ಒಪ್ಪಂದ",
    employment: "ಉದ್ಯೋಗ",
    commencement: "ಪ್ರಾರಂಭ",
    term: "ಅವಧಿ",
    "gross negligence": "ಭಾರಿ ನಿರ್ಲಕ್ಷ್ಯ",
    "written notice": "ಲೆಖಿತ ನೋಟಿಸ್",
    "payment in lieu of notice": "ನೋಟಿಸ್ ಬದಲಿಗೆ ಪಾವತಿ",
    misconduct: "ದುರಾಚರಣೆ",
    "breach of confidentiality": "ಗೌಪ್ಯತಾ ಉಲ್ಲಂಘನೆ",
    employer: "ನಿಯೋಜಕ",
    employee: "ನಿಯೋಜಿತ",
    exclusive: "ಪರಮ",
    sole: "ಏಕೈಕ",
    created: "ರಚಿಸಲಾದ",
    course: "ಅವಧಿ",
    "continue": "ಮುಂದುವರೆ",
    commence: "ಆರಂಭಿಸು",
    terminated: "ರದ್ದುಗೊಂಡ",
    prior: "ಮುನ್ಸೂಚನೆ",
    notice: "ಸೂಚನೆ",
    days: "ದಿನಗಳು",
    this: "ಇದು",
    made: "ಮಾಡಲಾಯಿತು",
    on: "ಮೇಲೆ",
    day: "ದಿನ",
    between: "ನಡುವೆ",
    pvt: "ಪಿ.ವಿ.ಟಿ",
    shall: "ಮಾಡಬೇಕು",
    any: "ಯಾವುದೇ",
    by: "ಮೂಲಕ",
    either: "ಏನಾದರೂ ಒಂದು",
    giving: "ಕೊಡುವುದು",
    or: "ಅಥವಾ",
    may: "ಬಹುದಾಗಿದೆ",
    case: "ಕೇಸ್",
    and: "ಮತ್ತು",
    laws: "ಕಾನೂನುಗಳು",
    of: "ಯ",
    india: "ಭಾರತ",
    survive: "ಉಳಿಯುತ್ತದೆ",
    for: "ಗಾಗಿ",
    two: "ಎರಡು",
    witness: "ಸಾಕ್ಷಿ",
    written: "ಲೆಖಿತ",
    above: "ಮೇಲೆ",
    in: "ಒಳಗೆ",
    without: "ಇಲ್ಲದೆ",
    technologies: "ತಂತ್ರಜ್ಞಾನಗಳು",
    sunrise: "ಸನ್‌ರೈಸ್",
    "summary": "ಸಾರಾಂಶ",
    "was made": "ಮಾಡಲಾಯಿತು",
    "on": "ಮೇಲೆ",
    "of": "ಯ",
    "Sunrise": "ಸನ್‌ರೈಸ್",
    "Pvt": "ಪಿ.ವಿ.ಟಿ",
    "until": "ವರೆಗೆ",
    "accordance": "ಅನುಸಾರ",
    "with": "ಜೊತೆಗೆ",
    "property": "ಆಸ್ತಿ",
    "confidentiality": "ಗೌಪ್ಯತೆ",
    "whereof": "ಇವುಗಳಿಂದ",
    "hereto": "ಇದಕ್ಕೆ",
    "is": "ಇದೆ",
    "the": "ದಿ",
    "be": "ಆಗಿರು",
    "terminate": "ರದ್ದುಗೊಳಿಸು",
    "lieu": "ಬದಲಿಗೆ",
    "governed": "ಆಡಳಿತದಡಿ",
    "a": "ಒಂದು",
    "period": "ಅವಧಿ",
    "years": "ವರ್ಷಗಳು",
    "have": "ಹೊಂದಿದೆ",
    "executed": "ಸಾಕ್ಷ್ಯಪಡಿಸಲಾಗಿದೆ",
    "date": "ದಿನಾಂಕ",
    "first": "ಮೊದಲ",
    "Key": "ಮುಖ್ಯ",
    "Legal": "ಕಾನೂನು",
    "Points": "ಅಂಶಗಳು"
    
  }
};


  async translateText(text: string, targetLang: string): Promise<string> {
    try {
      console.log(`[v0] SimpleTranslator: translating to ${targetLang}`)

      if (targetLang === "en") return text
      if (!text || text.trim().length === 0) return ""

      const translations = this.legalTranslations[targetLang]
      if (!translations) {
        console.log(`[v0] No translations available for ${targetLang}`)
        return text
      }

      // Create a safe copy of the text for processing
      let translatedText = text

      // Apply translations with word boundaries to avoid partial matches
      for (const [english, translated] of Object.entries(translations)) {
        try {
          const regex = new RegExp(`\\b${english.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\b`, "gi")
          translatedText = translatedText.replace(regex, translated)
        } catch (regexError) {
          console.error(`[v0] Regex error for term "${english}":`, regexError)
          // Skip this translation if regex fails
          continue
        }
      }

      // Add language-specific legal summary templates
      const templates = {
        hi: `कानूनी दस्तावेज़ सारांश:\n\n${translatedText}`,
        ta: `சட்ட ஆவண சுருக்கம்:\n\n${translatedText}`,
        te: `చట్టపరమైన పత్రం సారాంశం:\n\n${translatedText}`,
        kn: `ಕಾನೂನು ದಾಖಲೆ ಸಾರಾಂಶ:\n\n${translatedText}`,
        ml: `നിയമ രേഖ സംഗ്രഹം:\n\n${translatedText}`,
        gu: `કાનૂની દસ્તાવેજ સારાંશ:\n\n${translatedText}`,
      }

      const result = templates[targetLang as keyof typeof templates] || translatedText
      console.log(`[v0] Translation completed for ${targetLang}`)
      return result
    } catch (error) {
      console.error(`[v0] Translation error for ${targetLang}:`, error)
      throw error
    }
  }

  getLanguageName(code: string): string {
    return this.languageNames[code as keyof typeof this.languageNames] || code
  }

  getSupportedLanguages() {
    return Object.entries(this.languageNames).map(([code, name]) => ({
      code,
      name,
    }))
  }
}
